version: "3.9"

services:
  frontend:
    build: ./frontend/.
    image: frontend_angular
    container_name: frontend_angular
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - conduit-network
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - conduit-network

  backend:
    build: ./backend/.
    image: backend_express
    container_name: backend_express
    depends_on:
      - mongo
    environment:
      - "SECRET=${SECRET:?'Provide SECRET like: SECRET=<your_sercret> docker compose up'}"
      - MONGODB_URI=mongodb://mongo/conduit
    networks:
      conduit-network:
        aliases:
          - backend_express

  mongo:
    image: mongo:4
    container_name: db_mongo
    volumes:
      - ./mongo-data:/data/db
    expose:
      - 27017
    networks:
      - conduit-network

networks:
  conduit-network:
    driver: bridge

volumes:
  mongo-data:
